-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES FROM BOOK as B
JOIN BOOK_SALES as S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC